### PR TITLE
Create appveyor.yml

### PR DESCRIPTION
**Pull request by amallia**
Added MSVC CI integration. Repo needs to be enabled at appveyor.com

### CODE REVIEW

**Comment by lemire** [comment]
Ok. Let us see.

**Comment by lemire** [comment]
It works.

**Comment by amallia** [comment]
Awesome! You can add now a nice badge in the README

**Comment by lemire** [comment]
Ahead of you.

**Comment by lemire** [comment]
The badge is unimportant, but automatically checking that it builds under VS is important.

**Pull request merged**
