### PR TITLE
Master clang cl

### PR DESCRIPTION
**Pull request by pps83**

### CODE REVIEW

**Comment by lemire** [comment]
I know you from somewhere? :-)

Merging.

**Comment by pps83** [comment]
> I know you from somewhere? :-)
> 
> Merging.

Maybe, I'm from Montreal :)

**Comment by lemire** [comment]
You are? If not for the virus, I’d invite you for coffee.

**Comment by pps83** [comment]
> You are? If not for the virus, I’d invite you for coffee.

Would be my pleasure. Lately, I'm mostly away for work (California), but currently stuck in Asia

**Pull request merged**
