### PR TITLE
Clear padding bytes to ensure consistent output in simdfastpfor

### LINKED ISSUE #99: Some of the functions leave gaps in output buffers
For my own purpose I added unit tests and I got lots of failures because some of the codecs in FastPFor leave uninitialized gaps in output buffers when encoding. Namely, these are the codecs that fail in my tests:
simdfastpfor128, simdfastpfor256, varintg8iu, imdgroupsimple_ringbuf

This is the test I use:
```
TEST(Compression, testIntegerCodec)
{
    const size_t SZ = 12345;
    const uint32_t n = 1000;
    const int diff = 10;
    std::vector<uint32_t> in(SZ, n);
    for (auto& n : in)
        n += (rand32() % (diff * 2)) - diff;
    // in is an array of random numbers in the range of [990, 1010]

    for (auto& coder : coders::allCodecs())
    {
        if (coder.name() == "Null")
            return;
        LOG("coder: %s", std::string(coder.name()).c_str());
        std::vector<uint8_t> buf8(4 * (SZ + SZ / 4), 0xaa);  // << == init to 0xaa
        std::vector<uint32_t> buf32a, buf32b;
        size_t a = coder.encode(in, buf32a);
        size_t b = coder.encode(&in[0], in.size(), buf32b);
        size_t c = coder.encode(&in[0], in.size(), &buf8[0], buf8.size());
        buf8.resize(c);
        ASSERT_EQ(a, b);
        ASSERT_EQ(a, c);
        ASSERT_EQ(buf32a, buf32b);
        ASSERT_EQ(0, memcmp(buf32a.data(), buf8.data(), c));
    }
}
```

Most codecs pass the test, but those that fail have this memory diff:
image

as you can see, those that fail, set first 8 bytes, then 8 bytes left untouched. IMO, these codecs should be fixed to set that "untouuched" memory to something.

### PR DESCRIPTION
**Pull request by pps83**
partially fixes #99

### CODE REVIEW

**Comment by lemire** [comment]
We actually do not need this padding. Let me change that.

**Comment by pps83** [comment]
Yes, makes output buffer result dependent on the buffer alignment. Kind of very sketchy.

**Comment by pps83** [comment]
I updated the PR with similar fix for VarIntG8IU

**Comment by lemire** [comment]
This PR was merged into another PR, so dropping.

**Pull request closed without merging**
