### PR TITLE
Avoid linker errors when including simple8b_rle.h/simple9_rle.h/vsencoding.h headers from multiple files

### PR DESCRIPTION
**Pull request by pps83**

### CODE REVIEW

**Comment by lemire** [comment]
It seems that you are assuming C++17? See failed CI tests.

**Comment by pps83** [comment]
Yes, I see. I use c++20 in my code, so, it was ok on my side. The only way to make it work is to add .cpp files. Are you ok with that?

**Comment by pps83** [comment]
I think I have a better idea to fix it.

**Comment by pps83** [comment]
@lemire please recheck the PR

**Comment by lemire** [comment]
This should be fine. Thanks. Merging.

**Pull request merged**
